---
title: "lab5"
author: "Elaina"
date: "2024-05-04"
output: 
  html_document: 
    toc: true
    number_sections: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(foreach)
library(doParallel)
library(parallel)
```

# 函数

## 
实现函数
$$
\psi(x) = \left\{ \begin{array}{cl} x^2 & \mathrm{if}~|x|\leq 1\\
   2|x|-1 &\mathrm{if}~ |x| > 1\end{array}\right.
$$
. 画出(-5,5)区间内的图像
```{r}
# 定义函数
psi <- function(x) {
  ifelse(abs(x) <= 1, x^2, 2*abs(x) - 1)
}

# 生成 x 值
x <- seq(-5, 5, length.out = 1000)

# 计算 y 值
y <- psi(x)

# 绘制图像
plot(x, y, type = "l", col = "blue", lwd = 2, 
     xlab = "x", ylab = expression(psi(x)),
     main = "Plot of psi(x)")

# 添加网格线
grid()
```

## 
对函数
$$S_{k,n} = \sum_{i=1}^n \frac1{i^k}$$
，令$n=5000000, k=2,\dots,21$，分别计算$S_{k,n}$值并输出.比较使用并行和不使用并行的运行时间差异.
```{r}
# 定义函数计算 S_kn
S_kn <- function(k, n) {
  sum <- sum(1/(1:n)^k)
  return(sum)
}

# 定义 n 和 k 的取值
n <- 5000000
k_values <- 2:21

# 计算 S_kn 并输出结果
no_parallel_times <- numeric(length(k_values))
parallel_times <- numeric(length(k_values))

# 不使用并行
start_time <- Sys.time()  # 记录开始时间
S_kn_values_no_parallel <- sapply(k_values, function(k) S_kn(k, n))
end_time <- Sys.time()  # 记录结束时间
no_parallel_time <- end_time - start_time  # 计算运行时间

# 使用并行
start_time <- Sys.time()  # 记录开始时间
S_kn_values_parallel <- unlist(parallel::mclapply(k_values, function(k) S_kn(k, n)))
end_time <- Sys.time()  # 记录结束时间
parallel_time <- end_time - start_time  # 计算运行时间

# 输出结果
result <- data.frame(k_values, S_kn_values_no_parallel, S_kn_values_parallel)
print(result)
cat("No parallel time:", no_parallel_time, "\n")
cat("Parallel time:", parallel_time, "\n")
```

## 
随机游走时间序列的产生：
$$X_t = x_0 + t\mu + z_t$$
其中$x_0$是初值，$\mu$是漂移项，$z_t$是一组独立同分布的样本，均来自于标准正态分布。

### 
定义一个函数，输入参数为$N, x_0, \mu$和方差variance，输出为一个长度为$N$的随机游走时间序列。

### 
设随机种子为123，生成两个长度为100的随机游走时间序列，其中$x_0=10, \mu=0$，方差为0.0004。

### 
将这两个时间序列的图像画在一张图上。
```{r}
# 定义函数生成随机游走时间序列
random_walk <- function(N, x_0, mu, variance) {
  set.seed(123)  # 设置随机种子
  z <- rnorm(N, mean = 0, sd = sqrt(variance))  # 生成服从标准正态分布的随机数
  X <- x_0 + (1:N) * mu + cumsum(z)  # 计算随机游走时间序列
  return(X)
}

# 生成两个长度为100的随机游走时间序列
N <- 100
x_0 <- 10
mu <- 0
variance <- 0.0004

random_walk_1 <- random_walk(N, x_0, mu, variance)
random_walk_2 <- random_walk(N, x_0, mu, variance)

# 绘制随机游走时间序列的图像
plot(1:N, random_walk_1, type = "l", col = "blue", xlab = "Time", ylab = "Value", ylim = c(8, 12), main = "Random Walk Time Series")
lines(1:N, random_walk_2, col = "red")
legend("topright", legend = c("Random Walk 1", "Random Walk 2"), col = c("blue", "red"), lty = 1)

```